apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-example
  namespace: default
spec:
  limits:
  - type: Container
    max:
      cpu: "500m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "200m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
